version: '3.8'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    env_file:
      - ./.env
    depends_on:
      - postgres
    restart: always
    build: 
      context: ./ChatAppApi
      dockerfile: Dockerfile
    ports:
      - "8001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

  postgres:
    image: postgres
    restart: always
    env_file:
      - ./.env
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}